name : deploy command workflow
on:
  repository_dispatch:
    types: [deploy-command]
    
  workflow_dispatch:
    inputs:
      version:
        description: 'version' 
        default: ''       
        required: true        
      env:
        description: 'Env' 
        default: ''       
        required: true
  
env:
  ENVIRONMENT    : ${{ github.event.client_payload.slash_command.args.named.env || github.event.inputs.env  || 'nonprod' }}
  REGION         : eastus
  VERSION        : ${{ github.event.client_payload.slash_command.args.named.version || github.event.inputs.version  || '' }}
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: print 1
        run: |
          echo "${{toJson(github.event)}}"

      - name: print 2
        run: |
          echo "${{toJson(github.workflow)}}"

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        env:
            GEN_TOKEN: ${{ secrets.APP_KEY }}
        with:
          token:  ${{ env.GEN_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray

      # Get the branch name
      - name: Get the target enviornment name
        id: vars
        run: |
          enviornment=${{ github.event.client_payload.slash_command.args.named.enviornment }}
          region=${{ github.event.client_payload.slash_command.args.named.region }}
          echo "${{ github.event.client_payload.slash_command.args.named.enviornment }}"
          echo "${{ github.event.client_payload.slash_command.args.named.region }}"
          echo "${{ env.ENVIRONMENT }}"
          echo "${{ env.VERSION }}"
